### PR TITLE
transfer draft of onboarding documentation from hackmd

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@bthirion @man_shu

This is definitely work in progress but better have in on github than completely forgotten about in hackmd.

I would suggest to merge it as is and add content incrementally: either when we think about it or when we onboard new maintainers / contributors.

**Comment by man-shu** [comment]
I think I do not have the write access to this repo. 
I can add that to the TODO here once I get the access.

**Comment by Remi-Gau** [comment]
I have updated which repo the @nilearn/core team you are part of has access to. This repo should now be included: can you check if this helps?

**Comment by man-shu** [comment]
I still see this message on the PR.

Screenshot 2024-05-31 at 4 28 52 PM

Also tried fixing some typos in the README and got this:
```bash
ERROR: Permission to nilearn/nilearn_sandbox.git denied to man-shu.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Remi-Gau** [comment]
ha! 
the core team had only READ access to the repo: gave it maintainers access, this should fix it.

check again

**Comment by man-shu** [comment]
Yes! Works now

**Comment by man-shu** [comment]
Thanks!

**Comment by emdupre** [comment]
Sorry if I missed this discussion earlier this week, but : is there a reason to have this document in the sandbox ? I would have thought to place it in admin.

**Comment by bthirion** [comment]
+1 for putting it in admin repo.

**Comment by Remi-Gau** [comment]
Yeah you are correct: that would make more sense.

Transferring.

**Pull request closed without merging**
